// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (name, key_hash, key_prefix)
VALUES ($1, $2, $3)
RETURNING id, name, key_hash, key_prefix, created_at, disabled_at
`

type CreateAPIKeyParams struct {
	Name      string `json:"name"`
	KeyHash   string `json:"key_hash"`
	KeyPrefix string `json:"key_prefix"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey, arg.Name, arg.KeyHash, arg.KeyPrefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const disableAPIKey = `-- name: DisableAPIKey :exec
UPDATE api_keys SET disabled_at = now() WHERE id = $1 AND disabled_at IS NULL
`

func (q *Queries) DisableAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableAPIKey, id)
	return err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, name, key_hash, key_prefix, created_at, disabled_at FROM api_keys WHERE key_prefix = $1
`

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, keyPrefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, key_prefix, created_at, disabled_at
FROM api_keys
ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	CreatedAt  time.Time          `json:"created_at"`
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
}

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyPrefix,
			&i.CreatedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
