// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countDeliveriesByStatus = `-- name: CountDeliveriesByStatus :many
SELECT status, count(*)::bigint AS n FROM deliveries GROUP BY status
`

type CountDeliveriesByStatusRow struct {
	Status string `json:"status"`
	N      int64  `json:"n"`
}

func (q *Queries) CountDeliveriesByStatus(ctx context.Context) ([]CountDeliveriesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countDeliveriesByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDeliveriesByStatusRow{}
	for rows.Next() {
		var i CountDeliveriesByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDelivery = `-- name: GetDelivery :one
SELECT id, event_id, endpoint_id, status, attempt_count, next_attempt_at, locked_until, locked_by, last_status_code, last_error, delivered_at, created_at FROM deliveries WHERE id = $1
`

func (q *Queries) GetDelivery(ctx context.Context, id uuid.UUID) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDelivery, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.LockedBy,
		&i.LastStatusCode,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDeliveriesForEvent = `-- name: ListDeliveriesForEvent :many
SELECT id, event_id, endpoint_id, status, attempt_count, next_attempt_at, locked_until, locked_by, last_status_code, last_error, delivered_at, created_at FROM deliveries WHERE event_id = $1 ORDER BY created_at
`

func (q *Queries) ListDeliveriesForEvent(ctx context.Context, eventID uuid.UUID) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDeliveriesForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Delivery{}
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LockedUntil,
			&i.LockedBy,
			&i.LastStatusCode,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
