// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoints.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoints (
    name, url, secret_enc, filter, rate_limit_rps, timeout_ms,
    max_attempts, max_4xx_attempts, breaker_threshold, breaker_cooldown_s, allow_private
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, url, secret_enc, filter, status, rate_limit_rps, timeout_ms, max_attempts, max_4xx_attempts, breaker_threshold, breaker_cooldown_s, breaker_state, breaker_open_until, consecutive_failures, allow_private, created_at, updated_at
`

type CreateEndpointParams struct {
	Name             string          `json:"name"`
	Url              string          `json:"url"`
	SecretEnc        []byte          `json:"secret_enc"`
	Filter           json.RawMessage `json:"filter"`
	RateLimitRps     int32           `json:"rate_limit_rps"`
	TimeoutMs        int32           `json:"timeout_ms"`
	MaxAttempts      int32           `json:"max_attempts"`
	Max4xxAttempts   int32           `json:"max_4xx_attempts"`
	BreakerThreshold int32           `json:"breaker_threshold"`
	BreakerCooldownS int32           `json:"breaker_cooldown_s"`
	AllowPrivate     bool            `json:"allow_private"`
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, createEndpoint,
		arg.Name,
		arg.Url,
		arg.SecretEnc,
		arg.Filter,
		arg.RateLimitRps,
		arg.TimeoutMs,
		arg.MaxAttempts,
		arg.Max4xxAttempts,
		arg.BreakerThreshold,
		arg.BreakerCooldownS,
		arg.AllowPrivate,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.SecretEnc,
		&i.Filter,
		&i.Status,
		&i.RateLimitRps,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.Max4xxAttempts,
		&i.BreakerThreshold,
		&i.BreakerCooldownS,
		&i.BreakerState,
		&i.BreakerOpenUntil,
		&i.ConsecutiveFailures,
		&i.AllowPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEndpoint = `-- name: DeleteEndpoint :exec
DELETE FROM endpoints WHERE id = $1
`

func (q *Queries) DeleteEndpoint(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEndpoint, id)
	return err
}

const getEndpoint = `-- name: GetEndpoint :one
SELECT id, name, url, secret_enc, filter, status, rate_limit_rps, timeout_ms, max_attempts, max_4xx_attempts, breaker_threshold, breaker_cooldown_s, breaker_state, breaker_open_until, consecutive_failures, allow_private, created_at, updated_at FROM endpoints WHERE id = $1
`

func (q *Queries) GetEndpoint(ctx context.Context, id uuid.UUID) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpoint, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.SecretEnc,
		&i.Filter,
		&i.Status,
		&i.RateLimitRps,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.Max4xxAttempts,
		&i.BreakerThreshold,
		&i.BreakerCooldownS,
		&i.BreakerState,
		&i.BreakerOpenUntil,
		&i.ConsecutiveFailures,
		&i.AllowPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledEndpoints = `-- name: ListEnabledEndpoints :many
SELECT id, name, url, secret_enc, filter, status, rate_limit_rps, timeout_ms, max_attempts, max_4xx_attempts, breaker_threshold, breaker_cooldown_s, breaker_state, breaker_open_until, consecutive_failures, allow_private, created_at, updated_at FROM endpoints WHERE status = 'enabled'
`

func (q *Queries) ListEnabledEndpoints(ctx context.Context) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listEnabledEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.SecretEnc,
			&i.Filter,
			&i.Status,
			&i.RateLimitRps,
			&i.TimeoutMs,
			&i.MaxAttempts,
			&i.Max4xxAttempts,
			&i.BreakerThreshold,
			&i.BreakerCooldownS,
			&i.BreakerState,
			&i.BreakerOpenUntil,
			&i.ConsecutiveFailures,
			&i.AllowPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT id, name, url, secret_enc, filter, status, rate_limit_rps, timeout_ms, max_attempts, max_4xx_attempts, breaker_threshold, breaker_cooldown_s, breaker_state, breaker_open_until, consecutive_failures, allow_private, created_at, updated_at FROM endpoints ORDER BY created_at DESC
`

func (q *Queries) ListEndpoints(ctx context.Context) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.SecretEnc,
			&i.Filter,
			&i.Status,
			&i.RateLimitRps,
			&i.TimeoutMs,
			&i.MaxAttempts,
			&i.Max4xxAttempts,
			&i.BreakerThreshold,
			&i.BreakerCooldownS,
			&i.BreakerState,
			&i.BreakerOpenUntil,
			&i.ConsecutiveFailures,
			&i.AllowPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetBreaker = `-- name: ResetBreaker :exec
UPDATE endpoints SET
    breaker_state = 'closed',
    breaker_open_until = NULL,
    consecutive_failures = 0,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) ResetBreaker(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetBreaker, id)
	return err
}

const rotateEndpointSecret = `-- name: RotateEndpointSecret :one
UPDATE endpoints SET secret_enc = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, url, secret_enc, filter, status, rate_limit_rps, timeout_ms, max_attempts, max_4xx_attempts, breaker_threshold, breaker_cooldown_s, breaker_state, breaker_open_until, consecutive_failures, allow_private, created_at, updated_at
`

type RotateEndpointSecretParams struct {
	ID        uuid.UUID `json:"id"`
	SecretEnc []byte    `json:"secret_enc"`
}

func (q *Queries) RotateEndpointSecret(ctx context.Context, arg RotateEndpointSecretParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, rotateEndpointSecret, arg.ID, arg.SecretEnc)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.SecretEnc,
		&i.Filter,
		&i.Status,
		&i.RateLimitRps,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.Max4xxAttempts,
		&i.BreakerThreshold,
		&i.BreakerCooldownS,
		&i.BreakerState,
		&i.BreakerOpenUntil,
		&i.ConsecutiveFailures,
		&i.AllowPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const snapshotBreakerState = `-- name: SnapshotBreakerState :exec
UPDATE endpoints SET
    breaker_state        = $2,
    breaker_open_until    = $3,
    consecutive_failures  = $4,
    updated_at            = now()
WHERE id = $1
`

type SnapshotBreakerStateParams struct {
	ID                  uuid.UUID          `json:"id"`
	BreakerState        string             `json:"breaker_state"`
	BreakerOpenUntil    pgtype.Timestamptz `json:"breaker_open_until"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
}

func (q *Queries) SnapshotBreakerState(ctx context.Context, arg SnapshotBreakerStateParams) error {
	_, err := q.db.Exec(ctx, snapshotBreakerState,
		arg.ID,
		arg.BreakerState,
		arg.BreakerOpenUntil,
		arg.ConsecutiveFailures,
	)
	return err
}

const updateEndpoint = `-- name: UpdateEndpoint :one
UPDATE endpoints SET
    name           = COALESCE($1, name),
    url            = COALESCE($2, url),
    filter         = COALESCE($3, filter),
    status         = COALESCE($4, status),
    rate_limit_rps = COALESCE($5, rate_limit_rps),
    timeout_ms     = COALESCE($6, timeout_ms),
    max_attempts   = COALESCE($7, max_attempts),
    updated_at     = now()
WHERE id = $8
RETURNING id, name, url, secret_enc, filter, status, rate_limit_rps, timeout_ms, max_attempts, max_4xx_attempts, breaker_threshold, breaker_cooldown_s, breaker_state, breaker_open_until, consecutive_failures, allow_private, created_at, updated_at
`

type UpdateEndpointParams struct {
	Name         *string   `json:"name"`
	Url          *string   `json:"url"`
	Filter       []byte    `json:"filter"`
	Status       *string   `json:"status"`
	RateLimitRps *int32    `json:"rate_limit_rps"`
	TimeoutMs    *int32    `json:"timeout_ms"`
	MaxAttempts  *int32    `json:"max_attempts"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpoint,
		arg.Name,
		arg.Url,
		arg.Filter,
		arg.Status,
		arg.RateLimitRps,
		arg.TimeoutMs,
		arg.MaxAttempts,
		arg.ID,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.SecretEnc,
		&i.Filter,
		&i.Status,
		&i.RateLimitRps,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.Max4xxAttempts,
		&i.BreakerThreshold,
		&i.BreakerCooldownS,
		&i.BreakerState,
		&i.BreakerOpenUntil,
		&i.ConsecutiveFailures,
		&i.AllowPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
