// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const fanOutEvent = `-- name: FanOutEvent :execrows
INSERT INTO deliveries (event_id, endpoint_id)
SELECT $1, e.id
FROM endpoints e
WHERE e.status = 'enabled'
  AND (
    e.filter->>'mode' = 'all'
    OR EXISTS (
      SELECT 1
      FROM jsonb_array_elements_text(e.filter->'types') AS pat
      WHERE pat = '*'
         OR pat = $2::text
         OR (right(pat, 2) = '.*'
             AND left($2::text, length(pat) - 1) = left(pat, length(pat) - 1))
    )
  )
ON CONFLICT (event_id, endpoint_id) DO NOTHING
`

type FanOutEventParams struct {
	EventID   uuid.UUID `json:"event_id"`
	EventType string    `json:"event_type"`
}

// Fan an event out to every enabled endpoint whose filter matches its type.
// Idempotent: ON CONFLICT (event_id, endpoint_id) DO NOTHING.
func (q *Queries) FanOutEvent(ctx context.Context, arg FanOutEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, fanOutEvent, arg.EventID, arg.EventType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEvent = `-- name: GetEvent :one
SELECT id, api_key_id, type, payload, idempotency_key, occurred_at, received_at, fanned_out FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ApiKeyID,
		&i.Type,
		&i.Payload,
		&i.IdempotencyKey,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.FannedOut,
	)
	return i, err
}

const getEventByIdempotencyKey = `-- name: GetEventByIdempotencyKey :one
SELECT id, api_key_id, type, payload, idempotency_key, occurred_at, received_at, fanned_out FROM events
WHERE api_key_id = $1 AND idempotency_key = $2
`

type GetEventByIdempotencyKeyParams struct {
	ApiKeyID       uuid.UUID `json:"api_key_id"`
	IdempotencyKey *string   `json:"idempotency_key"`
}

func (q *Queries) GetEventByIdempotencyKey(ctx context.Context, arg GetEventByIdempotencyKeyParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByIdempotencyKey, arg.ApiKeyID, arg.IdempotencyKey)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ApiKeyID,
		&i.Type,
		&i.Payload,
		&i.IdempotencyKey,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.FannedOut,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (api_key_id, type, payload, idempotency_key, occurred_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, api_key_id, type, payload, idempotency_key, occurred_at, received_at, fanned_out
`

type InsertEventParams struct {
	ApiKeyID       uuid.UUID          `json:"api_key_id"`
	Type           string             `json:"type"`
	Payload        json.RawMessage    `json:"payload"`
	IdempotencyKey *string            `json:"idempotency_key"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.ApiKeyID,
		arg.Type,
		arg.Payload,
		arg.IdempotencyKey,
		arg.OccurredAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ApiKeyID,
		&i.Type,
		&i.Payload,
		&i.IdempotencyKey,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.FannedOut,
	)
	return i, err
}

const listUnfannedEventIDs = `-- name: ListUnfannedEventIDs :many
SELECT id FROM events
WHERE fanned_out = false
ORDER BY received_at
LIMIT $1
`

func (q *Queries) ListUnfannedEventIDs(ctx context.Context, limit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUnfannedEventIDs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventFannedOut = `-- name: MarkEventFannedOut :exec
UPDATE events SET fanned_out = true WHERE id = $1
`

func (q *Queries) MarkEventFannedOut(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEventFannedOut, id)
	return err
}
