// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	KeyPrefix  string             `json:"key_prefix"`
	CreatedAt  time.Time          `json:"created_at"`
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
}

type Attempt struct {
	ID              int64           `json:"id"`
	DeliveryID      uuid.UUID       `json:"delivery_id"`
	N               int32           `json:"n"`
	RequestHeaders  json.RawMessage `json:"request_headers"`
	StatusCode      *int32          `json:"status_code"`
	ResponseSnippet *string         `json:"response_snippet"`
	DurationMs      int32           `json:"duration_ms"`
	Outcome         string          `json:"outcome"`
	Error           *string         `json:"error"`
	AttemptedAt     time.Time       `json:"attempted_at"`
}

type Delivery struct {
	ID             uuid.UUID          `json:"id"`
	EventID        uuid.UUID          `json:"event_id"`
	EndpointID     uuid.UUID          `json:"endpoint_id"`
	Status         string             `json:"status"`
	AttemptCount   int32              `json:"attempt_count"`
	NextAttemptAt  time.Time          `json:"next_attempt_at"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	LockedBy       *string            `json:"locked_by"`
	LastStatusCode *int32             `json:"last_status_code"`
	LastError      *string            `json:"last_error"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt      time.Time          `json:"created_at"`
}

type Endpoint struct {
	ID                  uuid.UUID          `json:"id"`
	Name                string             `json:"name"`
	Url                 string             `json:"url"`
	SecretEnc           []byte             `json:"secret_enc"`
	Filter              json.RawMessage    `json:"filter"`
	Status              string             `json:"status"`
	RateLimitRps        int32              `json:"rate_limit_rps"`
	TimeoutMs           int32              `json:"timeout_ms"`
	MaxAttempts         int32              `json:"max_attempts"`
	Max4xxAttempts      int32              `json:"max_4xx_attempts"`
	BreakerThreshold    int32              `json:"breaker_threshold"`
	BreakerCooldownS    int32              `json:"breaker_cooldown_s"`
	BreakerState        string             `json:"breaker_state"`
	BreakerOpenUntil    pgtype.Timestamptz `json:"breaker_open_until"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	AllowPrivate        bool               `json:"allow_private"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
}

type Event struct {
	ID             uuid.UUID          `json:"id"`
	ApiKeyID       uuid.UUID          `json:"api_key_id"`
	Type           string             `json:"type"`
	Payload        json.RawMessage    `json:"payload"`
	IdempotencyKey *string            `json:"idempotency_key"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	ReceivedAt     time.Time          `json:"received_at"`
	FannedOut      bool               `json:"fanned_out"`
}
