// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const endpointHealth = `-- name: EndpointHealth :one
SELECT
    e.breaker_state AS breaker_state,
    e.breaker_open_until AS breaker_open_until,
    COALESCE(count(a.id) FILTER (WHERE a.outcome = 'success'), 0)::bigint AS successes_24h,
    COALESCE(count(a.id), 0)::bigint AS attempts_24h,
    COALESCE(percentile_disc(0.95) WITHIN GROUP (ORDER BY a.duration_ms), 0)::int AS p95_ms_24h
FROM endpoints e
LEFT JOIN deliveries d ON d.endpoint_id = e.id
LEFT JOIN attempts a ON a.delivery_id = d.id AND a.attempted_at >= now() - interval '24 hours'
WHERE e.id = $1
GROUP BY e.id
`

type EndpointHealthRow struct {
	BreakerState     string             `json:"breaker_state"`
	BreakerOpenUntil pgtype.Timestamptz `json:"breaker_open_until"`
	Successes24h     int64              `json:"successes_24h"`
	Attempts24h      int64              `json:"attempts_24h"`
	P95Ms24h         int32              `json:"p95_ms_24h"`
}

func (q *Queries) EndpointHealth(ctx context.Context, id uuid.UUID) (EndpointHealthRow, error) {
	row := q.db.QueryRow(ctx, endpointHealth, id)
	var i EndpointHealthRow
	err := row.Scan(
		&i.BreakerState,
		&i.BreakerOpenUntil,
		&i.Successes24h,
		&i.Attempts24h,
		&i.P95Ms24h,
	)
	return i, err
}

const listDeliveries = `-- name: ListDeliveries :many

SELECT id, event_id, endpoint_id, status, attempt_count, next_attempt_at, locked_until, locked_by, last_status_code, last_error, delivered_at, created_at, is_replay, replay_of FROM deliveries
WHERE ($1::uuid IS NULL OR endpoint_id = $1::uuid)
  AND ($2::uuid IS NULL OR event_id = $2::uuid)
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at < $5::timestamptz)
  AND (
    $6::timestamptz IS NULL
    OR created_at < $6::timestamptz
    OR (created_at = $6::timestamptz AND id < $7::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $8
`

type ListDeliveriesParams struct {
	EndpointID pgtype.UUID        `json:"endpoint_id"`
	EventID    pgtype.UUID        `json:"event_id"`
	Status     *string            `json:"status"`
	FromTs     pgtype.Timestamptz `json:"from_ts"`
	ToTs       pgtype.Timestamptz `json:"to_ts"`
	CursorTs   pgtype.Timestamptz `json:"cursor_ts"`
	CursorID   pgtype.UUID        `json:"cursor_id"`
	Lim        int32              `json:"lim"`
}

// Read-side queries: filtered + keyset-paginated feeds, replay, endpoint health.
func (q *Queries) ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDeliveries,
		arg.EndpointID,
		arg.EventID,
		arg.Status,
		arg.FromTs,
		arg.ToTs,
		arg.CursorTs,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Delivery{}
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LockedUntil,
			&i.LockedBy,
			&i.LastStatusCode,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.IsReplay,
			&i.ReplayOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, api_key_id, type, payload, idempotency_key, occurred_at, received_at, fanned_out FROM events
WHERE ($1::text IS NULL OR type = $1::text)
  AND ($2::timestamptz IS NULL OR received_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR received_at < $3::timestamptz)
  AND (
    $4::timestamptz IS NULL
    OR received_at < $4::timestamptz
    OR (received_at = $4::timestamptz AND id < $5::uuid)
  )
ORDER BY received_at DESC, id DESC
LIMIT $6
`

type ListEventsParams struct {
	Type     *string            `json:"type"`
	FromTs   pgtype.Timestamptz `json:"from_ts"`
	ToTs     pgtype.Timestamptz `json:"to_ts"`
	CursorTs pgtype.Timestamptz `json:"cursor_ts"`
	CursorID pgtype.UUID        `json:"cursor_id"`
	Lim      int32              `json:"lim"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents,
		arg.Type,
		arg.FromTs,
		arg.ToTs,
		arg.CursorTs,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.Type,
			&i.Payload,
			&i.IdempotencyKey,
			&i.OccurredAt,
			&i.ReceivedAt,
			&i.FannedOut,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replayDelivery = `-- name: ReplayDelivery :one
INSERT INTO deliveries (event_id, endpoint_id, status, next_attempt_at, is_replay, replay_of)
SELECT src.event_id, src.endpoint_id, 'pending', now(), true, src.id
FROM deliveries src WHERE src.id = $1
RETURNING id, event_id, endpoint_id, status, attempt_count, next_attempt_at, locked_until, locked_by, last_status_code, last_error, delivered_at, created_at, is_replay, replay_of
`

func (q *Queries) ReplayDelivery(ctx context.Context, id uuid.UUID) (Delivery, error) {
	row := q.db.QueryRow(ctx, replayDelivery, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.LockedBy,
		&i.LastStatusCode,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.IsReplay,
		&i.ReplayOf,
	)
	return i, err
}
