// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error)
	DeleteEndpoint(ctx context.Context, id uuid.UUID) error
	DisableAPIKey(ctx context.Context, id uuid.UUID) error
	GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error)
	GetEndpoint(ctx context.Context, id uuid.UUID) (Endpoint, error)
	ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error)
	ListEnabledEndpoints(ctx context.Context) ([]Endpoint, error)
	ListEndpoints(ctx context.Context) ([]Endpoint, error)
	ResetBreaker(ctx context.Context, id uuid.UUID) error
	RotateEndpointSecret(ctx context.Context, arg RotateEndpointSecretParams) (Endpoint, error)
	SnapshotBreakerState(ctx context.Context, arg SnapshotBreakerStateParams) error
	UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error)
}

var _ Querier = (*Queries)(nil)
