// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const claimDueDeliveries = `-- name: ClaimDueDeliveries :many
WITH due AS (
    SELECT id FROM deliveries
    WHERE status IN ('pending', 'failed', 'blocked') AND next_attempt_at <= now()
    ORDER BY next_attempt_at
    FOR UPDATE SKIP LOCKED
    LIMIT $3
)
UPDATE deliveries d
SET status        = 'delivering',
    locked_until  = now() + ($1::int * interval '1 second'),
    locked_by     = $2,
    attempt_count = attempt_count + 1
FROM due
WHERE d.id = due.id
RETURNING d.id
`

type ClaimDueDeliveriesParams struct {
	LeaseSeconds int32   `json:"lease_seconds"`
	LockedBy     *string `json:"locked_by"`
	BatchSize    int32   `json:"batch_size"`
}

// Claim a batch of due deliveries: mark them 'delivering', take a lease, and
// bump attempt_count now so a crash can't cause unbounded retries. SKIP LOCKED
// lets many workers/instances pull disjoint batches with no coordinator.
func (q *Queries) ClaimDueDeliveries(ctx context.Context, arg ClaimDueDeliveriesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, claimDueDeliveries, arg.LeaseSeconds, arg.LockedBy, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeliveryDispatch = `-- name: GetDeliveryDispatch :one
SELECT
    d.id             AS delivery_id,
    d.attempt_count  AS attempt_count,
    d.event_id       AS event_id,
    e.id             AS endpoint_id,
    e.url            AS url,
    e.secret_enc     AS secret_enc,
    e.timeout_ms     AS timeout_ms,
    e.max_attempts   AS max_attempts,
    e.max_4xx_attempts AS max_4xx_attempts,
    e.rate_limit_rps AS rate_limit_rps,
    e.breaker_threshold AS breaker_threshold,
    e.breaker_cooldown_s AS breaker_cooldown_s,
    e.status         AS endpoint_status,
    e.allow_private  AS allow_private,
    ev.type          AS event_type,
    ev.payload       AS payload,
    ev.api_key_id    AS api_key_id
FROM deliveries d
JOIN endpoints e ON e.id = d.endpoint_id
JOIN events ev ON ev.id = d.event_id
WHERE d.id = $1
`

type GetDeliveryDispatchRow struct {
	DeliveryID       uuid.UUID       `json:"delivery_id"`
	AttemptCount     int32           `json:"attempt_count"`
	EventID          uuid.UUID       `json:"event_id"`
	EndpointID       uuid.UUID       `json:"endpoint_id"`
	Url              string          `json:"url"`
	SecretEnc        []byte          `json:"secret_enc"`
	TimeoutMs        int32           `json:"timeout_ms"`
	MaxAttempts      int32           `json:"max_attempts"`
	Max4xxAttempts   int32           `json:"max_4xx_attempts"`
	RateLimitRps     int32           `json:"rate_limit_rps"`
	BreakerThreshold int32           `json:"breaker_threshold"`
	BreakerCooldownS int32           `json:"breaker_cooldown_s"`
	EndpointStatus   string          `json:"endpoint_status"`
	AllowPrivate     bool            `json:"allow_private"`
	EventType        string          `json:"event_type"`
	Payload          json.RawMessage `json:"payload"`
	ApiKeyID         uuid.UUID       `json:"api_key_id"`
}

// Everything the delivery pipeline needs, in one row.
func (q *Queries) GetDeliveryDispatch(ctx context.Context, id uuid.UUID) (GetDeliveryDispatchRow, error) {
	row := q.db.QueryRow(ctx, getDeliveryDispatch, id)
	var i GetDeliveryDispatchRow
	err := row.Scan(
		&i.DeliveryID,
		&i.AttemptCount,
		&i.EventID,
		&i.EndpointID,
		&i.Url,
		&i.SecretEnc,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.Max4xxAttempts,
		&i.RateLimitRps,
		&i.BreakerThreshold,
		&i.BreakerCooldownS,
		&i.EndpointStatus,
		&i.AllowPrivate,
		&i.EventType,
		&i.Payload,
		&i.ApiKeyID,
	)
	return i, err
}

const insertAttempt = `-- name: InsertAttempt :exec
INSERT INTO attempts (delivery_id, n, request_headers, status_code, response_snippet, duration_ms, outcome, error)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAttemptParams struct {
	DeliveryID      uuid.UUID       `json:"delivery_id"`
	N               int32           `json:"n"`
	RequestHeaders  json.RawMessage `json:"request_headers"`
	StatusCode      *int32          `json:"status_code"`
	ResponseSnippet *string         `json:"response_snippet"`
	DurationMs      int32           `json:"duration_ms"`
	Outcome         string          `json:"outcome"`
	Error           *string         `json:"error"`
}

func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) error {
	_, err := q.db.Exec(ctx, insertAttempt,
		arg.DeliveryID,
		arg.N,
		arg.RequestHeaders,
		arg.StatusCode,
		arg.ResponseSnippet,
		arg.DurationMs,
		arg.Outcome,
		arg.Error,
	)
	return err
}

const listAttempts = `-- name: ListAttempts :many
SELECT id, delivery_id, n, request_headers, status_code, response_snippet, duration_ms, outcome, error, attempted_at FROM attempts WHERE delivery_id = $1 ORDER BY n
`

func (q *Queries) ListAttempts(ctx context.Context, deliveryID uuid.UUID) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, listAttempts, deliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attempt{}
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.N,
			&i.RequestHeaders,
			&i.StatusCode,
			&i.ResponseSnippet,
			&i.DurationMs,
			&i.Outcome,
			&i.Error,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryBlocked = `-- name: MarkDeliveryBlocked :exec
UPDATE deliveries
SET status = 'blocked', next_attempt_at = $2, locked_until = NULL, locked_by = NULL,
    last_error = $3, attempt_count = GREATEST(attempt_count - 1, 0)
WHERE id = $1
`

type MarkDeliveryBlockedParams struct {
	ID            uuid.UUID `json:"id"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
	LastError     *string   `json:"last_error"`
}

func (q *Queries) MarkDeliveryBlocked(ctx context.Context, arg MarkDeliveryBlockedParams) error {
	_, err := q.db.Exec(ctx, markDeliveryBlocked, arg.ID, arg.NextAttemptAt, arg.LastError)
	return err
}

const markDeliveryDead = `-- name: MarkDeliveryDead :exec
UPDATE deliveries
SET status = 'dead', locked_until = NULL, locked_by = NULL,
    last_status_code = $2, last_error = $3
WHERE id = $1
`

type MarkDeliveryDeadParams struct {
	ID             uuid.UUID `json:"id"`
	LastStatusCode *int32    `json:"last_status_code"`
	LastError      *string   `json:"last_error"`
}

func (q *Queries) MarkDeliveryDead(ctx context.Context, arg MarkDeliveryDeadParams) error {
	_, err := q.db.Exec(ctx, markDeliveryDead, arg.ID, arg.LastStatusCode, arg.LastError)
	return err
}

const markDeliveryFailed = `-- name: MarkDeliveryFailed :exec
UPDATE deliveries
SET status = 'failed', next_attempt_at = $2, locked_until = NULL, locked_by = NULL,
    last_status_code = $3, last_error = $4
WHERE id = $1
`

type MarkDeliveryFailedParams struct {
	ID             uuid.UUID `json:"id"`
	NextAttemptAt  time.Time `json:"next_attempt_at"`
	LastStatusCode *int32    `json:"last_status_code"`
	LastError      *string   `json:"last_error"`
}

func (q *Queries) MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, markDeliveryFailed,
		arg.ID,
		arg.NextAttemptAt,
		arg.LastStatusCode,
		arg.LastError,
	)
	return err
}

const markDeliverySucceeded = `-- name: MarkDeliverySucceeded :exec
UPDATE deliveries
SET status = 'succeeded', delivered_at = now(), locked_until = NULL, locked_by = NULL,
    last_status_code = $2, last_error = NULL
WHERE id = $1
`

type MarkDeliverySucceededParams struct {
	ID             uuid.UUID `json:"id"`
	LastStatusCode *int32    `json:"last_status_code"`
}

func (q *Queries) MarkDeliverySucceeded(ctx context.Context, arg MarkDeliverySucceededParams) error {
	_, err := q.db.Exec(ctx, markDeliverySucceeded, arg.ID, arg.LastStatusCode)
	return err
}

const reapStaleDeliveries = `-- name: ReapStaleDeliveries :many
UPDATE deliveries
SET status = 'failed', next_attempt_at = now(), locked_until = NULL, locked_by = NULL,
    last_error = 'worker_lost'
WHERE status = 'delivering' AND locked_until < now()
RETURNING id, attempt_count, endpoint_id
`

type ReapStaleDeliveriesRow struct {
	ID           uuid.UUID `json:"id"`
	AttemptCount int32     `json:"attempt_count"`
	EndpointID   uuid.UUID `json:"endpoint_id"`
}

// Flip leases that outlived their worker back to 'failed' so they're retried.
func (q *Queries) ReapStaleDeliveries(ctx context.Context) ([]ReapStaleDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, reapStaleDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReapStaleDeliveriesRow{}
	for rows.Next() {
		var i ReapStaleDeliveriesRow
		if err := rows.Scan(&i.ID, &i.AttemptCount, &i.EndpointID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseDelivery = `-- name: ReleaseDelivery :exec
UPDATE deliveries
SET status = 'pending', next_attempt_at = $2, locked_until = NULL, locked_by = NULL,
    attempt_count = GREATEST(attempt_count - 1, 0)
WHERE id = $1
`

type ReleaseDeliveryParams struct {
	ID            uuid.UUID `json:"id"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
}

// Release a claimed delivery without an HTTP attempt (paused / rate-limited):
// give back the attempt_count that ClaimDueDeliveries pre-charged.
func (q *Queries) ReleaseDelivery(ctx context.Context, arg ReleaseDeliveryParams) error {
	_, err := q.db.Exec(ctx, releaseDelivery, arg.ID, arg.NextAttemptAt)
	return err
}
